### ISSUE TITLE
Installation fails after 1.5.0-1 release

### ISSUE THREAD

**Issue by ruddan** [aristanetworks/cloudvision-python#11]
Not possible to install/upgrade cloudvision-python via pip since release 1.5.0-1.

Workaround:
`pip install 'cloudvision!=1.5.0.post1'`

```
debug-cloudvision# pipenv install cloudvision
Installing cloudvision...
Error:  An error occurred while installing cloudvision!
Error text: Collecting cloudvision
  Using cached cloudvision-1.5.0-1.tar.gz (151 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4y/hlz9dntn5_q1b6z_5zk93mj4lt2gx5/T/pip-install-9zdi21q2/cloudvision_6925c7e856a64ed59bd7f989bad802cd/setup.py", line 12, in <module>
          with open("requirements.txt", "r") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

This is likely caused by a bug in cloudvision. Report this to its maintainers.
✘ Installation Failed

```

**Comment by cianmcgrath** [comment]
Thanks for opening the issue, I am currently investigating this. Will update when I can

**Comment by cianmcgrath** [comment]
I believe this has been resolved. `pip install --upgrade cloudvision` now works.
The requirements files were not being bundled in the source distribution due to an oversight, which will be addressed.
Please use the `--no-cache-dir` option if installation has been attempted and failed to force the download of `1.5.0-post3`
