### ISSUE TITLE
Passing token directly to GRPCClient causes error

### ISSUE THREAD

**Issue by qduk** [aristanetworks/cloudvision-python#3]
When passing a token string directly to GRPCClient, I get an error from RPC.

```
Traceback (most recent call last):
  File "/opt/nautobot/plugins/cloudvision_chatbot/cloudvision_chatbot/test.py", line 28, in <module>
    test_test = test()
  File "/opt/nautobot/plugins/cloudvision_chatbot/cloudvision_chatbot/test.py", line 21, in test
    for batch in client.get(query):
  File "/opt/nautobot/lib/python3.9/site-packages/cloudvision/Connector/grpc_client/grpcClient.py", line 197, in <genexpr>
    return (self.decode_batch(nb) for nb in stream)
  File "/opt/nautobot/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/nautobot/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1624296069.697848021","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1624296069.697841974","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```

**Comment by cianmcgrath** [comment]
There was a bug previously when this was opened where the tokenValue was not used for the auth check and may have tried to create an insecure channel as a result. 
This was fixed here: https://github.com/aristanetworks/cloudvision-python/commit/fb0b5d72a7d151c41774d58584f2b3beef3810a0
Have you hit this issue with the more recent versions that have this change?
